linux aarch64 (ARM)
dlshriver/intercepts pull request #8
Opened 2023-05-08 03:30 UTC by nilnullzip

Here is support for aarch64. I created a new `handler_ptr.c` that employs pointers instead of coding addresses inline. I added Makefile target `linux-aarch64` to generate the hex. This commit passes the `pytest` suite and also worked in my application.

In adding this support, I minimized changes to your code vs trying to introduce my methods everywhere as I didn't know what you would want to do there. I think perhaps `handler_ptr.c` could work for all instruction architectures and replace `handler.c`. Also I introduced some changes to how the hex is extracted that should be more universal.

2023-06-03 12:46 UTC, dlshriver requested changes
This looks pretty good to me. Could you run `./scripts/style.sh --format` on everything to make sure it passes the style check?

I'm in the process of getting an ARM system so that I can actually exercise your code. I probably won't merge this into `main` until that happens. I'd also like to have ARM support in the CI pipeline, but I'm not going to block this while waiting for that to happen.

2023-06-03 12:46 UTC, dlshriver commented on handler/handler_ptr.c
Neat idea!

2023-06-03 20:59 UTC, nilnullzip commented
Black formatting fixed.

I am running intercepts on an 8GB Raspberry Pi4. Available for $120 on Amazon. Smaller memory configuration probably works too. I don't think it will work on earlier RPi as I don't think those are 64 bit.

Let me know if there is anything else you need. Thanks for the great project! -Juan

2023-07-08 14:46 UTC, dlshriver approved these changes

2023-07-08 14:50 UTC, merged